compiled config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,32 +1,58 @@
-version: 2.1
-
-orbs:
-    node: circleci/node@7.2.1
-
+# Orb 'circleci/node@3.0.1' resolved to 'circleci/node@3.0.1'
+version: 2
 jobs:
-    build-and-test:
-        docker: # image to run on
-            - image: cimg/node:18.20.5
-        resource_class: xlarge # how much CPU/RAM
-        parallelism: 15 # nodes to split test suite over
-        steps:
-            - checkout
-            - node/install-packages:
-                pkg-manager: yarn
-            - run: mkdir ~/junit
-            - run: # split test suite over the parallel nodes
-                name: Test application
-                command: |
-                    TEST=$(circleci tests glob "src/__tests__/*.js" | circleci tests split --split-by=timings)
-                    yarn test $TEST
-            - run:
-                command: cp junit.xml ~/junit/
-                when: always
-            - store_test_results:
-                path: ~/junit
-            - store_artifacts:
-                path: ~/junit
+  build-and-test:
+    docker:
+    - image: cimg/node:18.20.5
+    resource_class: xlarge
+    parallelism: 15
+    steps:
+    - checkout
+    - run:
+        command: |
+          if [ ! -f "package.json" ]; then
+            echo
+            echo "---"
+            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
+            echo "---"
+            echo
+            echo "Current directory: $(pwd)"
+            echo
+            echo
+            echo "List directory: "
+            echo
+            ls
+            exit 1
+          fi
+        name: Checking for package.json.
+        working_directory: ~/project
+    - restore_cache:
+        keys:
+        - node-deps-v1-{{ .Branch }}-{{ checksum "~/project/yarn.lock" }}
+    - run:
+        command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  yarn install --frozen-lockfile\nfi\n"
+        name: Installing YARN packages
+        working_directory: ~/project
+    - save_cache:
+        key: node-deps-v1-{{ .Branch }}-{{ checksum "~/project/yarn.lock" }}
+        paths:
+        - ~/project/node_modules
+    - run:
+        command: mkdir ~/junit
+    - run:
+        name: Test application
+        command: |
+          TEST=$(circleci tests glob "src/__tests__/*.js" | circleci tests split --split-by=timings)
+          yarn test $TEST
+    - run:
+        command: cp junit.xml ~/junit/
+        when: always
+    - store_test_results:
+        path: ~/junit
+    - store_artifacts:
+        path: ~/junit
 workflows:
-    build-and-test:
-      jobs:
-        - build-and-test
+  build-and-test:
+    jobs:
+    - build-and-test
+  version: 2
